# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CineHive' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'naveridlogin-sdk-ios'

  # Pods for CineHive

  # Youtube Player 라이브러리
  use_modular_headers!
  pod 'youtube-ios-player-helper'
  pod 'KakaoSDKCommon'
  pod 'KakaoSDKAuth'
  pod 'KakaoSDKUser'
  pod 'KakaoSDKShare'
  pod 'GoogleSignInSwiftSupport'

end
