# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CineHive' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CineHive

  # Youtube Player 라이브러리
  pod 'youtube-ios-player-helper'

end
